### ISSUE TITLE
remove the color-map from annotations

### ISSUE THREAD

**Issue by JianqiaoXiao** [lxx1991/VS-ReID#3]
"After download, you need to remove the color-map from annotations."
Hello, thank you for publishing the source code. Can you tell me what this step is for? Remove the color-map from annotations, what are the annotations next?

**Comment by lxx1991** [comment]
Since opencv could not directly read the index from the png file with color-map, you may need to use following Matlab statements to remove the color-map.

```Matlab
ann, cmap = imread('annfile.png')
imwrite(ann, 'new_annfile.png')
```

**Comment by JianqiaoXiao** [comment]
Sincerely thank you for your reply. I removed the color-map like you said, but I got new error like this:
=> loading checkpoint 'models/MP2S.pth.tar'
=> loaded checkpoint
bbox_i.shape:  (3, 4)
occ_instance:  1
occ_instance:  3
Traceback (most recent call last):
  File "/home/aita/AITA2/xiaojq/Project/VS-ReID/davis_test2.py", line 506, in <module>
    main()
  File "/home/aita/AITA2/xiaojq/Project/VS-ReID/davis_test2.py", line 453, in main
    if (IoU(bbox_now, bbox_i[occ_instance]) > bbox_occ_th):
IndexError: index 3 is out of bounds for axis 0 with size 3=> loading checkpoint 'models/MP2S.pth.tar'
=> loaded checkpoint
bbox_i.shape:  (3, 4)
occ_instance:  1
occ_instance:  3
Traceback (most recent call last):
  File "/home/aita/AITA2/xiaojq/Project/VS-ReID/davis_test2.py", line 506, in <module>
    main()
  File "/home/aita/AITA2/xiaojq/Project/VS-ReID/davis_test2.py", line 453, in main
    if (IoU(bbox_now, bbox_i[occ_instance]) > bbox_occ_th):
IndexError: index 3 is out of bounds for axis 0 with size 3

##############################################
I print some information for this error

**Comment by JasonDu1993** [comment]
> Since opencv could not directly read the index from the png file with color-map, you may need to use following Matlab statements to remove the color-map.
> 
> ```matlab
> ann, cmap = imread('annfile.png')
> imwrite(ann, 'new_annfile.png')
> ```

Hello, imread and imwrite from which python package? What is the removed the color-map image  shape if I read the "new_annfile.png" with opencv?  And can you provide a script to deal with the problem? Thanks.
