### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by pankajvshrma** [lxx1991/VS-ReID#4]
I removed color map from annotations. Also generated bidirectional flow for DAVIS JPEGIMAGES folder.

I am getting following error when I try to test for test_dev list -

```
=> loading checkpoint 'models/MP2S.pth.tar'
=> loaded checkpoint
Traceback (most recent call last):
  File "davis_test.py", line 516, in <module>
    main()
  File "davis_test.py", line 399, in main
    pred_prob[th] = label_to_prob(np.zeros_like(label_0, np.uint8), instance_num)
  File "~/VS-ReID/core/utils/bbox.py", line 35, in label_to_prob
    prob = np.zeros(label.shape + (channels * 2, ))
MemoryError
```

When I checked GPU(Titan X) usage it is using only:
```

| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 23%   38C    P8    10W / 250W |   1169MiB / 11171MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
```
|=============================================================================|
|    0     25396      C   python3                                     1159MiB |
+-----------------------------------------------------------------------------+

 Can you suggest what is going wrong? I assume it is not using gpu memory to full extent.

**Comment by lxx1991** [comment]
It seems there is something wrong with numpy, which is related to the memory instead of gpu memory.

Could you print the value of 'label.shape' and 'channels'?
