### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by pankajvshrma** [lxx1991/VS-ReID#5]
Hi,
I am getting following error while trying to run test_dev from DAVIS dataset. I have generated bi-directional flows and also removed color map from annotations earlier.

=> loading checkpoint 'models/MP2S.pth.tar'
=> loaded checkpoint
Traceback (most recent call last):
  File "davis_test.py", line 516, in <module>
    main()
  File "davis_test.py", line 419, in main
    predict(1, frames_num, 1, range(instance_num))
  File "davis_test.py", line 50, in predict
    warp_prob = flo.get_warp_label(flow1[th - 1], flow2[th], combine_prob(pred_prob[th - 1]))
  File "~/VS-ReID/core/utils/flow.py", line 52, in get_warp_label
    label2[valid, :] = label1[dx[valid].round().astype(int), dy[valid].round().astype(int), :]
IndexError: index 480 is out of bounds for axis 0 with size 480

Can you suggest what is happening?

**Comment by bach-zouk** [comment]
Hi,

Did you adapt the code as I cant seem to match the line in the main file.. Could you confirm
 predict(1, frames_num, 1, range(instance_num))

**Comment by dailenson** [comment]
can you tell me how to generated bi-directional flows? I use flownet2 to get the optical flow,but I don't know how to get the bi-directional flows.
